#!/usr/bin/env node
/**
 * HRManager 5.0 — Installation Wizard
 * Run with: npm run install-wizard  (from the /backend folder)
 *
 * Walks the administrator through:
 *   1. Database connection details
 *   2. Company information
 *   3. Currency selection  <-- required by product spec
 *   4. Timezone & pay frequency
 *   5. Admin account creation
 *   6. Writes backend/.env, creates the database if needed,
 *      syncs tables, and seeds defaults.
 */
const fs = require('fs');
const path = require('path');
const inquirer = require('inquirer');
const mysql = require('mysql2/promise');
const currencies = require('../src/config/currencies');

const ENV_PATH = path.join(__dirname, '..', '.env');

function line() { console.log('─'.repeat(60)); }

async function main() {
  console.log('\n╔══════════════════════════════════════════════════════╗');
  console.log('║        HRManager 5.0 — Installation Wizard            ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');

  if (fs.existsSync(ENV_PATH)) {
    const { proceed } = await inquirer.prompt([{
      type: 'confirm',
      name: 'proceed',
      message: 'A configuration (.env) already exists. Re-running will overwrite it. Continue?',
      default: false
    }]);
    if (!proceed) {
      console.log('Installation cancelled.');
      process.exit(0);
    }
  }

  line();
  console.log('STEP 1 of 5 — Database Connection');
  line();
  const dbAnswers = await inquirer.prompt([
    { type: 'input', name: 'DB_HOST', message: 'MySQL host:', default: '127.0.0.1' },
    { type: 'input', name: 'DB_PORT', message: 'MySQL port:', default: '3306' },
    { type: 'input', name: 'DB_NAME', message: 'Database name:', default: 'hrmanager5' },
    { type: 'input', name: 'DB_USER', message: 'MySQL username:', default: 'root' },
    { type: 'password', name: 'DB_PASSWORD', message: 'MySQL password:', mask: '*' }
  ]);

  line();
  console.log('STEP 2 of 5 — Company Information');
  line();
  const companyAnswers = await inquirer.prompt([
    { type: 'input', name: 'COMPANY_NAME', message: 'Company name:', default: 'My Company Ltd' },
    {
      type: 'list',
      name: 'PAY_FREQUENCY',
      message: 'Default pay frequency:',
      choices: ['Monthly', 'Bi-Weekly', 'Weekly'],
      default: 'Monthly'
    },
    { type: 'input', name: 'DEFAULT_TIMEZONE', message: 'Timezone (e.g. Africa/Lagos, UTC):', default: 'UTC' }
  ]);

  line();
  console.log('STEP 3 of 5 — Currency Selection');
  line();
  const { DEFAULT_CURRENCY } = await inquirer.prompt([{
    type: 'list',
    name: 'DEFAULT_CURRENCY',
    message: 'Select the default currency for payroll and reports:',
    choices: currencies.map(c => ({ name: `${c.code} — ${c.name} (${c.symbol})`, value: c.code })),
    pageSize: 12
  }]);
  const currencyMeta = currencies.find(c => c.code === DEFAULT_CURRENCY);

  line();
  console.log('STEP 4 of 5 — Administrator Account');
  line();
  const adminAnswers = await inquirer.prompt([
    { type: 'input', name: 'ADMIN_FIRST_NAME', message: 'Admin first name:', default: 'System' },
    { type: 'input', name: 'ADMIN_LAST_NAME', message: 'Admin last name:', default: 'Administrator' },
    { type: 'input', name: 'ADMIN_EMAIL', message: 'Admin email (used to log in):', default: 'admin@example.com' },
    {
      type: 'password',
      name: 'ADMIN_PASSWORD',
      message: 'Admin password (min 8 characters):',
      mask: '*',
      validate: v => v.length >= 8 || 'Password must be at least 8 characters'
    }
  ]);

  line();
  console.log('STEP 5 of 5 — Security & App URLs');
  line();
  const secAnswers = await inquirer.prompt([
    { type: 'input', name: 'PORT', message: 'Backend API port:', default: '5000' },
    { type: 'input', name: 'CLIENT_URL', message: 'Frontend URL (for CORS):', default: 'http://localhost:5173' }
  ]);

  const jwtSecret = require('crypto').randomBytes(32).toString('hex');
  const jwtRefreshSecret = require('crypto').randomBytes(32).toString('hex');

  const envContent = `# Auto-generated by HRManager 5.0 Installation Wizard on ${new Date().toISOString()}
NODE_ENV=production
PORT=${secAnswers.PORT}
APP_URL=http://localhost:${secAnswers.PORT}
CLIENT_URL=${secAnswers.CLIENT_URL}
APP_NAME=HRManager 5.0

DB_HOST=${dbAnswers.DB_HOST}
DB_PORT=${dbAnswers.DB_PORT}
DB_NAME=${dbAnswers.DB_NAME}
DB_USER=${dbAnswers.DB_USER}
DB_PASSWORD=${dbAnswers.DB_PASSWORD}

JWT_SECRET=${jwtSecret}
JWT_EXPIRES_IN=8h
JWT_REFRESH_SECRET=${jwtRefreshSecret}
JWT_REFRESH_EXPIRES_IN=7d
BCRYPT_SALT_ROUNDS=10

COMPANY_NAME=${companyAnswers.COMPANY_NAME}
DEFAULT_CURRENCY=${currencyMeta.code}
DEFAULT_CURRENCY_SYMBOL=${currencyMeta.symbol}
DEFAULT_TIMEZONE=${companyAnswers.DEFAULT_TIMEZONE}
DEFAULT_LOCALE=en-US
PAY_FREQUENCY=${companyAnswers.PAY_FREQUENCY}

ADMIN_EMAIL=${adminAnswers.ADMIN_EMAIL}
ADMIN_PASSWORD=${adminAnswers.ADMIN_PASSWORD}
ADMIN_FIRST_NAME=${adminAnswers.ADMIN_FIRST_NAME}
ADMIN_LAST_NAME=${adminAnswers.ADMIN_LAST_NAME}
`;

  console.log('\nCreating database if it does not already exist...');
  try {
    const conn = await mysql.createConnection({
      host: dbAnswers.DB_HOST,
      port: dbAnswers.DB_PORT,
      user: dbAnswers.DB_USER,
      password: dbAnswers.DB_PASSWORD
    });
    await conn.query(`CREATE DATABASE IF NOT EXISTS \`${dbAnswers.DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
    await conn.end();
    console.log(`✔ Database "${dbAnswers.DB_NAME}" is ready`);
  } catch (err) {
    console.error('✘ Could not connect to MySQL with the details provided:', err.message);
    console.error('  Please check your MySQL server is running and the credentials are correct, then re-run the wizard.');
    process.exit(1);
  }

  fs.writeFileSync(ENV_PATH, envContent, 'utf8');
  console.log('✔ Configuration saved to backend/.env');

  console.log('\nCreating tables and seeding default data...');
  // Re-exec in a fresh process so dotenv picks up the freshly written .env
  process.env.NODE_ENV = 'production';
  delete require.cache[require.resolve('../src/config/db')];
  const { execSync } = require('child_process');
  try {
    execSync('node src/seeders/seed.js', { cwd: path.join(__dirname, '..'), stdio: 'inherit' });
  } catch (err) {
    console.error('✘ Seeding failed. You can retry manually with: npm run seed');
    process.exit(1);
  }

  line();
  console.log('✅ Installation complete!');
  line();
  console.log(`Company:   ${companyAnswers.COMPANY_NAME}`);
  console.log(`Currency:  ${currencyMeta.code} (${currencyMeta.symbol})`);
  console.log(`Admin:     ${adminAnswers.ADMIN_EMAIL}`);
  console.log('\nStart the API with:  npm start');
  console.log(`Then log in to the frontend at ${secAnswers.CLIENT_URL} with the admin email/password above.\n`);
}

main().catch(err => {
  console.error('Installation failed:', err);
  process.exit(1);
});
